ERROR:root:D:\Python Projects\report_portal\Scripts\Portal/web_excel_files/Stock.xlsx
INFO:django.utils.autoreload:D:\Python Projects\report_portal\Scripts\Portal\reports\supports.py changed, reloading.
INFO:root:D:\Python Projects\report_portal\Scripts\Portal/web_excel_files/Stock13-Aug-2022-16:51:11.xlsx
ERROR:django.request:Internal Server Error: /stock/
Traceback (most recent call last):
  File "D:\Python Projects\report_portal\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python Projects\report_portal\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python Projects\report_portal\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Python Projects\report_portal\Scripts\Portal\reports\decorators.py", line 29, in wrapper_func
    return view_func(request, *args,**kwargs)
  File "D:\Python Projects\report_portal\Scripts\Portal\reports\views.py", line 752, in stock
    excel_file_path = excel_generator(
  File "D:\Python Projects\report_portal\Scripts\Portal\reports\supports.py", line 65, in excel_generator
    generate_excel = pd.ExcelWriter(
  File "D:\Python Projects\report_portal\lib\site-packages\pandas\io\excel\_xlsxwriter.py", line 191, in __init__
    super().__init__(
  File "D:\Python Projects\report_portal\lib\site-packages\pandas\io\excel\_base.py", line 1106, in __init__
    self.handles = get_handle(
  File "D:\Python Projects\report_portal\lib\site-packages\pandas\io\common.py", line 795, in get_handle
    handle = open(handle, ioargs.mode)
OSError: [Errno 22] Invalid argument: 'D:\\Python Projects\\report_portal\\Scripts\\Portal/web_excel_files/Stock13-Aug-2022-16:51:11.xlsx'
INFO:django.utils.autoreload:D:\Python Projects\report_portal\Scripts\Portal\reports\supports.py changed, reloading.
INFO:root:D:\Python Projects\report_portal\Scripts\Portal/web_excel_files/Stock13-Aug-2022-16:51:37.xlsx
ERROR:django.request:Internal Server Error: /stock/
Traceback (most recent call last):
  File "D:\Python Projects\report_portal\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python Projects\report_portal\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python Projects\report_portal\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Python Projects\report_portal\Scripts\Portal\reports\decorators.py", line 29, in wrapper_func
    return view_func(request, *args,**kwargs)
  File "D:\Python Projects\report_portal\Scripts\Portal\reports\views.py", line 752, in stock
    excel_file_path = excel_generator(
  File "D:\Python Projects\report_portal\Scripts\Portal\reports\supports.py", line 65, in excel_generator
    generate_excel = pd.ExcelWriter(
  File "D:\Python Projects\report_portal\lib\site-packages\pandas\io\excel\_xlsxwriter.py", line 191, in __init__
    super().__init__(
  File "D:\Python Projects\report_portal\lib\site-packages\pandas\io\excel\_base.py", line 1106, in __init__
    self.handles = get_handle(
  File "D:\Python Projects\report_portal\lib\site-packages\pandas\io\common.py", line 795, in get_handle
    handle = open(handle, ioargs.mode)
OSError: [Errno 22] Invalid argument: 'D:\\Python Projects\\report_portal\\Scripts\\Portal/web_excel_files/Stock13-Aug-2022-16:51:37.xlsx'
INFO:django.utils.autoreload:D:\Python Projects\report_portal\Scripts\Portal\reports\supports.py changed, reloading.
INFO:root:D:\Python Projects\report_portal\Scripts\Portal/web_excel_files/Stock13-Aug-2022-16-52-23.xlsx
INFO:django.utils.autoreload:D:\Python Projects\report_portal\Scripts\Portal\reports\supports.py changed, reloading.
INFO:root:D:\Python Projects\report_portal\Scripts\Portal/web_excel_files/Stock-13-Aug-2022-16-52-36.xlsx
INFO:django.utils.autoreload:D:\Python Projects\report_portal\Scripts\Portal\reports\supports.py changed, reloading.
INFO:root:D:\Python Projects\report_portal\Scripts\Portal/web_excel_files/Stock-13-Aug-2022-16-54-04-089689.xlsx
INFO:django.utils.autoreload:D:\Python Projects\report_portal\Scripts\Portal\reports\supports.py changed, reloading.
